import { Button, CardActions } from '@hypothesis/frontend-shared';
import { useCallback, useEffect, useId, useMemo, useState } from 'preact/hooks';

import type { APIShareflowSegmentation, RecordItem } from '../../../types/api';
import { readJSONFile } from '../../../shared/read-json-file';
import { isObject } from '../../../shared/is-object';
import { withServices } from '../../service-context';
import type { RecordingService } from '../../services/recording';
import type { ToastMessengerService } from '../../services/toast-messenger';
import { useSidebarStore } from '../../store';
import CircularProgress from '../CircularProgress';
import FileInput from './FileInput';

/**
 * Parse a file generated by the annotation exporter and return the extracted
 * annotations.
 */
export async function readExportFile(file: File): Promise<APIShareflowSegmentation> {
  let json;
  try {
    json = await readJSONFile(file);
  } catch (err) {
    throw new Error('Not a valid JSON file');
  }

  // Perform some very rudimentary validation of the file content, just enough
  // to catch issues where the user picked the wrong kind of JSON file.
  if (
    !isObject(json) ||
    !Array.isArray((json as any).sections) ||
    !(json as any).sections.every(
      (section: any) =>
        typeof section.title === 'string' &&
        typeof section.description === 'string' &&
        Array.isArray(section.steps_id) &&
        section.steps_id.every((id: any) => typeof id === 'string')
    )
  ) {
    throw new Error('Not a valid Shareflow Segmentation JSON file');
  }

  return (json as APIShareflowSegmentation);
}

export type ImportShareflowSegmentationProps = {
  recordingService: RecordingService;
  toastMessenger: ToastMessengerService;
};

/**
 * Content of "Import" tab of annotation share dialog.
 *
 * This allows the user to select a previously exported file of annotations
 * and initiate an import via {@link ImportAnnotationsService}.
 */
function ImportShareflowSegmentation({
  // importAnnotationsService,
  recordingService,
  toastMessenger,
}: ImportShareflowSegmentationProps) {
  const [file, setFile] = useState<File | null>(null);

  // Annotations extracted from `file`.
  const [shareflowSegmentation, setShareflowSegmentation] = useState<APIShareflowSegmentation | null>(
    null,
  );
  const [error, setError] = useState<string | null>(null);

  const store = useSidebarStore();
  const focusedRecordItem = store.focusedRecordItemId();
  const [recordItem, setRecordItem] = useState<RecordItem | null>(null);
  const recordSteps = store.recordSteps();
  const currentUser = store.profile().userid;

  useEffect(()=> {
    if (focusedRecordItem) {
      const recordItem = store.getRecordItemById(focusedRecordItem);
      setRecordItem(recordItem);
    }
  }, [focusedRecordItem]);

  // Parse input file, extract annotations and update the user list.
  useEffect(() => {
    if (!currentUser || !file) {
      return;
    }
    setError(null);
    readExportFile(file)
      .then(shareflowSegmentation => {
        const stepIds = recordSteps.map(s => s.id);
        shareflowSegmentation.sections.map(section => {
          section.steps_id.map(
            sectionId => {
              if (!stepIds.includes(sectionId)) {
                throw new Error("Missing items from import file in shareflow");
              }
            }
          );
        })
        setShareflowSegmentation(shareflowSegmentation);
      })
      .catch(err => {
        setError(err.message);
      });
  }, [currentUser, file]);

  const importSegmentation = useCallback(() => {
    if (recordItem) {
      if (recordItem.userid !== currentUser) {
        toastMessenger.error("It is not your shareflow", {
          autoDismiss: false,
        });
      }
      recordingService.updateRecord(recordItem.id, {
        extra: shareflowSegmentation
      });
    } else {
      toastMessenger.error("invaild shareflow", {
        autoDismiss: false,
      });
    }
  }, [recordItem, shareflowSegmentation, currentUser]);

  const fileInputId = useId();

  if (!currentUser) {
    // TODO - Make "Log in" a link.
    return (
      <p data-testid="log-in-message">You must log in to import shareflow segmentation.</p>
    );
  }

  // In order to perform an import, we need:
  //
  //  1. A group to import into
  //  2. A frame from which to get the document URI and metadata
  //  3. Existing annotations for the group loaded so we can de-duplicate against
  //     them
  //  4. A file to import from and a selection of what to import
  //     (`importAnnotations` will be falsey if this is not the case).
  const importReady = Boolean(
    store.focusedGroup() &&
      store.defaultContentFrame() &&
      store.hasFetchedAnnotations() &&
      !store.isFetchingAnnotations() &&
      !error &&
      file &&
      importSegmentation,
  );

  // True if we're validating a JSON file after it has been selected.
  const parseInProgress = file && !shareflowSegmentation && !error;

  // True if we're validating or importing.
  const importsPending = store.importsPending();
  const importsTotal = store.importsTotal();
  const importsCompleted = importsTotal - importsPending;

  const busy = parseInProgress || importsPending > 0;

  const importProgress =
    importsPending > 0
      ? Math.round((importsCompleted / importsTotal) * 100)
      : null;

  return (
    <>
    {recordItem ? (
      <>
        <p className="text-color-text-light mb-3">
          version: {recordItem.extra && recordItem.extra?.version}
        </p>
        <label htmlFor={fileInputId} className="font-medium">
          Select Shareflow Segmentation file:
        </label>
        <FileInput onFileSelected={setFile} disabled={busy} id={fileInputId} />
        {error && (
          // TODO - Add a support link here.
          <p data-testid="error-info">
            <b>Unable to find shareflow segementation to import:</b> {error}
          </p>
        )}
        <CardActions>
          {importProgress !== null && (
            <span data-testid="progress-text" className="text-grey-6">
              {importProgress}% complete
            </span>
          )}
          <Button
            data-testid="import-button"
            disabled={!importReady || busy}
            onClick={importSegmentation}
            variant="primary"
          >
            {importProgress !== null && (
              <CircularProgress size={22} value={importProgress} />
            )}
            Import
          </Button>
        </CardActions>
      </>
    ) : (
      <>
        You haven't selected any shareflow to import!
      </>
    )}
    </>
  );
}

export default withServices(ImportShareflowSegmentation, [
  "recordingService",
  'toastMessenger',
]);
